### ISSUE TITLE
Make rebooting optional

### ISSUE THREAD

**Issue by cgoubert** [SineQuaNonSoftware/puppet-proxmox#6]
https://github.com/SineQuaNonSoftware/puppet-proxmox/blob/aa2c24aeccb8f1d3675e18ce4759fa8dfb90e64e/manifests/install.pp#L25

Pass a parameter that enables rebooting, just not do it by default. Also, reboot resource defaults to "immediately", maybe delay that until the end of the puppet run at least ?

**Comment by cornuwel** [comment]
I think only the reboot after installing proxmox-ve should be mandatory (kernel change). The network should not.
And yes, pushing the reboot to the end of the run is fine.

**Comment by cornuwel** [comment]
This is already done isn't it?

**Comment by cgoubert** [comment]
Not completely. I switched it to be done at the end of the run, but did not make it optional in any way.

**Comment by cornuwel** [comment]
Well, since you also changed how we handle the network, the only moment that reboot will be triggered is right after installing the proxmox kernel for the first time.
I personnally wouldn't use that option and can't think of a reason you'd want to have a partially working admin interface and unusable server until you reboot it yourself?

**Comment by cgoubert** [comment]
Network changes are applied through an ifup/down and not a reboot.
This reboot will be triggered on update too.
